name: Test

on :
  workflow_run:
    workflows: ["Train"]
    types: 
        - completed

jobs:

    evaluate:
        runs-on: ubuntu-latest
        steps:
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            -
                name: Pull Docker Image
                run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/score_test:v1

            - 
                name: Test model
                run: |
                    OUTPUT=$(docker run ${{ secrets.DOCKERHUB_USERNAME }}/score_test:v1)
                    echo "Score:"
                    echo "$OUTPUT"
                    if [[ `echo "$OUTPUT 0.40" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
        