name: Test

on :
  workflow_run:
    workflows: [ Train ]
    types: 
        - completed

jobs:

    evaluate:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Recognize sha ref
                id: sharef
                run: |
                    if [ "$EVENT" == 'workflow_run' ]
                    then
                    echo "::set-output name=sha::$(echo ${{github.event.workflow_run.head_sha}})"
                    fi
                env:
                    EVENT: ${{ github.event_name }}
                    REF: ${{ github.ref }}
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            -
                name: Pull Docker Image
                run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/score_test:v1

            - 
                name: Test model
                run: |
                    OUTPUT=$(docker run ${{ secrets.DOCKERHUB_USERNAME }}/score_test:v1)
                    echo "Score:"
                    echo "$OUTPUT"
                    if [[ `echo "$OUTPUT 0.30" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
        
            - 
                name: Check model score
                uses: LouisBrunner/checks-action@v1.1.1
                if: always()
                with:
                    name: Check model score
                    conclusion: ${{ job.status }}
                    sha: ${{ steps.sharef.outputs.sha }}
                    token: ${{ secrets.GITHUB_TOKEN }}
        